### ISSUE TITLE
Error with TypeScript 3.5, "An accessor cannot be declared in an ambient context."

### ISSUE THREAD

**Issue by tsvetomir** [marijnh/orderedmap#10]
The types introduced in #6 include [a getter](https://github.com/marijnh/orderedmap/blob/e93cd8b2bdcbdbc7851940cd7ca50f07ac44e36b/types/index.d.ts#L24) that is not supported in TypeScript versions 3.6 and earlier. This particular change in the compiler output was [widely criticized](https://github.com/microsoft/TypeScript/issues/33939) at the time.

While these TypeScript versions are pretty old (~2 years) by now, they're still used by some projects. Our particular issue is with the Kendo UI Editor for Angular when running in Angular 8.x projects, but it may not be limited to it.

My suggestion is to replace it with a `readonly` field to remain compatible with older versions of TypeScript.

The only downside to that is that inheriting `OrderedMap` will require using a field for overriding `size`. I'm not sure if inheriting the class is a common scenario for the library. _Edit: I've just noticed that the constructor is marked as private and extending the class is not supported._

```patch
diff --git a/types/index.d.ts b/types/index.d.ts
index 551e742..fdc372c 100644
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -21,7 +21,7 @@ declare class OrderedMap<T = any> {
 
   subtract(map: MapLike<T>): OrderedMap<T>
 
-  get size(): number
+  readonly size: number
 
   static from<T>(map: MapLike<T>): OrderedMap<T>
 }
```

**Comment by marijnh** [comment]
Attached patch makes this a regular property.

**Comment by tsvetomir** [comment]
Thanks! 🍻
