### ISSUE TITLE
The type definition does not match the source code

### ISSUE THREAD

**Issue by latin-1** [marijnh/orderedmap#11]
https://github.com/marijnh/orderedmap/commit/5c1541c31ac88a7f38a49e27eb5707756377386b

Should use `export =` for `module.exports =`.

This commit also breaks [@types/prosemirror-view](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/37361b150206a89d1f96e45cf582dc24be84f6b9/types/prosemirror-model/index.d.ts#L14).

**Comment by marijnh** [comment]
I'm not sure what TypeScripts `import OrderedMap = require('orderedmap')` is supposed to be, but I'm moving towards standard ES modules, and as such am trying to do away with this kind of weird interop mess. The ES module in orderedmap exports the class as default export, so this definition definitely matches _that_ source code. If you know of a way to write the type definitions that works with both CommonJS `module.exports` and ES `export default`, I'd be interested to hear.

**Comment by marijnh** [comment]
1.1.7 provides separate .d.ts files for the CommonJS and ES module files, which seems to avoid this problem.
