### ISSUE TITLE
Any plans for implementing Symbol.iterator support?

### ISSUE THREAD

**Issue by razyalov** [marijnh/orderedmap#16]
WIth modern linters, especially with TypeScript code, (e.g. the `unicorn/recommended` rules), I've noticed it trying to replace my `.forEach` loops for a `for (const item of orderedMapObject)` which breaks my code.
Any reason to not implement support for the `Symbol.iterator` method so that using `for()` loops will work smoothly with this library?
If this is accepted, I don't PR-ing a fix for this.

**Comment by marijnh** [comment]
A lint that makes baseless assumptions about objects and breaks code sounds like a pretty bad lint.

I don't think iterating over these is an important enough thing to add _another_ method for it, and I don't want to make the library depend on `Symbol` at this point.

**Comment by razyalov** [comment]
> A lint that makes baseless assumptions about objects and breaks code sounds like a pretty bad lint.
> 
I agree ☝️ 
> 
> 
> I don't think iterating over these is an important enough thing to add _another_ method for it, and I don't want to make the library depend on `Symbol` at this point.

Fair enough. I'll scratch this change.
