### ISSUE TITLE
This module probably needs to be updated to account for the new `linebreakReplacement` property

### ISSUE THREAD

**Issue by gnemtsov** [marijnh/orderedmap#21]
When I upgrade `prosemirror-model` to latest version, I get type errors. It complains of some incompatibility between modules
> Type 'import("/project/node_modules/orderedmap/dist/index").default<import("/project/packages/prosemirror/node_modules/prosemirror-model/dist/index").NodeSpec>' is not assignable to type 'import("/project/node_modules/orderedmap/dist/index").default<import("/project/node_modules/prosemirror-model/dist/index").NodeSpec>'
> ...
> Property 'linebreakReplacement' is missing in type 'import("/project/node_modules/prosemirror-model/dist/index").Schema<any, any>' but required in type 'import("/project/packages/prosemirror/node_modules/prosemirror-model/dist/index").Schema<any, any>'

**Comment by marijnh** [comment]
The problem is that you are loading multiple copies of prosemirror-model (one under project/node_modules, and one under project/packages/prosemirror/node_modules). This package doesn't reference `NodeSpec` at all -- it is just a generic type parameter in that error message.

**Comment by gnemtsov** [comment]
@marijnh Thanks for taking a look!

Maybe its unrelated to this specific package but it still looks like some misconfiguration between prosemirror packages. I use all latest prosemirror packages and doesn't have anything listed while running `yarn outdated`. Still, there are type errors about missing `linebreakReplacement` property.

I do use multiple copies of the prosemirror packages because I have a monorepo with multiple packages. I've never had any issues up until now. I always double-check that all my monorepo packages use exact same versions.

When I run `yarn why` I see that indeed there is an outdated `prosemirror-model` package at the root level. But it's hoisted by `yarn` because some other prosemirror packages use it from what I can tell. 

For example, I see that `prosemirror-view` (v1.33.8) has `"prosemirror-transform": "^1.1.0"` and this installs `prosemirror-transoform` v1.7.3 that, in turn, has `"prosemirror-model": "^1.0.0"` and here we go, `prosemirror-model` v1.19.2 is installed and hoisted by yarn. In the end, it breaks types from my understanding because of incompatibility between different `prosemirror-model` version. Maybe you need to up versions of `prosemirror-model` in other packages that are using it.

**Comment by gnemtsov** [comment]
Looked more into it. In `yarn.lock` I see
```
prosemirror-model@^1.0.0, prosemirror-model@^1.16.0:
  version "1.19.2"
  resolved "https://registry.yarnpkg.com/prosemirror-model/-/prosemirror-model-1.19.2.tgz#297c9ecfb103154e605f0dbaf3cc72ee32ca0ad5"
  integrity sha512-RXl0Waiss4YtJAUY3NzKH0xkJmsZupCIccqcIFoLTIKFlKNbIvFDRl27/kQy1FP8iUAxrjRRfIVvOebnnXJgqQ==
  dependencies:
    orderedmap "^2.0.0"

prosemirror-model@^1.20.0, prosemirror-model@^1.21.0, prosemirror-model@^1.22.0:
  version "1.22.0"
  resolved "https://registry.yarnpkg.com/prosemirror-model/-/prosemirror-model-1.22.0.tgz#29490c1b71150493480130713f323eadac4ec419"
  integrity sha512-sUPJS+6p+fD5XK81ddeDdNKMg4ltaE3jo0vOZT8wEGExDT1RwA7ACB0tgPayI4an/b43pYXTQiu7HWg40PDlDA==
  dependencies:
    orderedmap "^2.0.0"
```

So it's due to `yarn` keeping old version for some of prosemirror packages. After I've manually updated resolution records in `yarn.lock` to resolve to `1.22.0`, the issue was fixed. 

I guess, because of the incompatibility of the new `prosemirror-model` versions with the old ones, the versions of other packages should be increased and other packages should be updated to use `"prosemirror-model": ^1.21.0` to tell `yarn` to resolve it to newer versions. Otherwise `yarn` can keep older versions in `yarn.lock` and the types can be broken like in my case.
