### ISSUE TITLE
Use named export for ES module compatibility

### ISSUE THREAD

**Issue by bradleyayers** [marijnh/orderedmap#3]
Currently this package exports a class as the module, which isn't supported in ES modules. A simple solution is to just use a named export, i.e.

```
exports.OrderedMap = OrderedMap;
```

Commonjs consumers would then import via:

```
const { OrderedMap } = require('orderedmap');
```

The motivation for this is to smooth the path for packages wanting to adopt ES modules that depend on this package.

**Comment by marijnh** [comment]
See #4
